wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: time
      6:
      - 3
    - 1: val_loss_vs_time
      5: 1
      6:
      - 1
      - 3
    - 1: train_loss_vs_time
      5: 1
      6:
      - 1
      - 3
    python_version: 3.11.5
    start_time: 1706897353.321015
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.13.9
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.001
log_every_n_epochs:
  desc: null
  value: 25
max_epochs:
  desc: null
  value: 100000
max_time:
  desc: null
  value: 60
model_type:
  desc: null
  value: low_rank
sparsity:
  desc: null
  value: 0.2
